export enum UnderstandCategory {
  FAR_RIGHT = "far-right",
  PATRIARCHY = "patriarchy",
  WHITE_SUPREMACY = "white-supremacy",
  COLONIALISM = "colonialism",
  ECOLOGY = "ecology",
  SPECISM = "specism",
  OTHER = "other",
}

export const understandCatgerories = [
  UnderstandCategory.FAR_RIGHT,
  UnderstandCategory.PATRIARCHY,
  UnderstandCategory.WHITE_SUPREMACY,
  UnderstandCategory.COLONIALISM,
  UnderstandCategory.ECOLOGY,
  UnderstandCategory.SPECISM,
  UnderstandCategory.OTHER,
];


export const categoryKeyWords: Record<UnderstandCategory, string[]> = {
  [UnderstandCategory.FAR_RIGHT]: [
    "extreme-droite",
    "obscurantisme",
    "bollore",
    "ugo-palheta",
    "fascisation",
    "fascistes",
    "fasciste",
    "fascisme",
    "matin-brun",
    "antisemitisme",
    "big-brother",
    "technofascisme",
    "antifa",
    "anti-fa",
    "anti-repression",
    "anti-cra",
  ],
  [UnderstandCategory.COLONIALISM]: [
    "imperialistes",
    "impérialiste",
    "impérialisme",
    "palestine",
    "gaza",
    "antisionisme",
    "decoloniser",
    "empire",
  ],
  [UnderstandCategory.ECOLOGY]: [
    "l-eau",
    "nucleaire",
    "lgv",
    "soulevements",
    "bouturage",
  ],
  [UnderstandCategory.WHITE_SUPREMACY]: [
    "arabite",
    "racisme",
    "antiracisme",
    "islam",
    "blanchite",
    "dibondo",
  ],
  [UnderstandCategory.PATRIARCHY]: [
    "queer",
    "queerness",
    "patriarcat",
    "feminisme",
    "feministe",
    "viol",
    "masculinistes",
    "masculiniste",
    "dibondo",
  ],
  [UnderstandCategory.SPECISM]: [
    "specisme",
    "antispecisme",
    "vegan",
    "cuisine-vegetale",
  ],
  [UnderstandCategory.OTHER]: [],
};