/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SafiaDahaniLesExtremesDroitesContemporainesRouteImport } from './routes/safia-dahani-les-extremes-droites-contemporaines'
import { Route as QuiSommesNousRouteImport } from './routes/qui-sommes-nous'
import { Route as PresseRouteImport } from './routes/presse'
import { Route as PolitiqueDeConfidentialiteRouteImport } from './routes/politique-de-confidentialite'
import { Route as ParticiperAuFestivalRouteImport } from './routes/participer-au-festival'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as LesFourmilieresRouteImport } from './routes/les-fourmilieres'
import { Route as LeProgrammeRouteImport } from './routes/le-programme'
import { Route as LaFourmiliereDeLodeveRouteImport } from './routes/la-fourmiliere-de-lodeve'
import { Route as LaFourmiliereBruleRouteImport } from './routes/la-fourmiliere-brule'
import { Route as LaCharteRouteImport } from './routes/la-charte'
import { Route as FestivalDesLuttesPopulairesRouteImport } from './routes/festival-des-luttes-populaires'
import { Route as EntretienEmmanuelNegrierRouteImport } from './routes/entretien-emmanuel-negrier'
import { Route as DesLendemainsMeilleursRouteImport } from './routes/des-lendemains-meilleurs'
import { Route as BatailleCulturelleHistoireDu14JuilletRouteImport } from './routes/bataille-culturelle-histoire-du-14-juillet'
import { Route as BatailleCulturelleDesLuttesPaysannesRouteImport } from './routes/bataille-culturelle-des-luttes-paysannes'
import { Route as R30SeptembreHalleTropismeRouteImport } from './routes/30-septembre-halle-tropisme'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgrammeIndexRouteImport } from './routes/programme/index'
import { Route as ProgrammeUuidRouteImport } from './routes/programme/$uuid'

const SafiaDahaniLesExtremesDroitesContemporainesRoute =
  SafiaDahaniLesExtremesDroitesContemporainesRouteImport.update({
    id: '/safia-dahani-les-extremes-droites-contemporaines',
    path: '/safia-dahani-les-extremes-droites-contemporaines',
    getParentRoute: () => rootRouteImport,
  } as any)
const QuiSommesNousRoute = QuiSommesNousRouteImport.update({
  id: '/qui-sommes-nous',
  path: '/qui-sommes-nous',
  getParentRoute: () => rootRouteImport,
} as any)
const PresseRoute = PresseRouteImport.update({
  id: '/presse',
  path: '/presse',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueDeConfidentialiteRoute =
  PolitiqueDeConfidentialiteRouteImport.update({
    id: '/politique-de-confidentialite',
    path: '/politique-de-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const ParticiperAuFestivalRoute = ParticiperAuFestivalRouteImport.update({
  id: '/participer-au-festival',
  path: '/participer-au-festival',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const LesFourmilieresRoute = LesFourmilieresRouteImport.update({
  id: '/les-fourmilieres',
  path: '/les-fourmilieres',
  getParentRoute: () => rootRouteImport,
} as any)
const LeProgrammeRoute = LeProgrammeRouteImport.update({
  id: '/le-programme',
  path: '/le-programme',
  getParentRoute: () => rootRouteImport,
} as any)
const LaFourmiliereDeLodeveRoute = LaFourmiliereDeLodeveRouteImport.update({
  id: '/la-fourmiliere-de-lodeve',
  path: '/la-fourmiliere-de-lodeve',
  getParentRoute: () => rootRouteImport,
} as any)
const LaFourmiliereBruleRoute = LaFourmiliereBruleRouteImport.update({
  id: '/la-fourmiliere-brule',
  path: '/la-fourmiliere-brule',
  getParentRoute: () => rootRouteImport,
} as any)
const LaCharteRoute = LaCharteRouteImport.update({
  id: '/la-charte',
  path: '/la-charte',
  getParentRoute: () => rootRouteImport,
} as any)
const FestivalDesLuttesPopulairesRoute =
  FestivalDesLuttesPopulairesRouteImport.update({
    id: '/festival-des-luttes-populaires',
    path: '/festival-des-luttes-populaires',
    getParentRoute: () => rootRouteImport,
  } as any)
const EntretienEmmanuelNegrierRoute =
  EntretienEmmanuelNegrierRouteImport.update({
    id: '/entretien-emmanuel-negrier',
    path: '/entretien-emmanuel-negrier',
    getParentRoute: () => rootRouteImport,
  } as any)
const DesLendemainsMeilleursRoute = DesLendemainsMeilleursRouteImport.update({
  id: '/des-lendemains-meilleurs',
  path: '/des-lendemains-meilleurs',
  getParentRoute: () => rootRouteImport,
} as any)
const BatailleCulturelleHistoireDu14JuilletRoute =
  BatailleCulturelleHistoireDu14JuilletRouteImport.update({
    id: '/bataille-culturelle-histoire-du-14-juillet',
    path: '/bataille-culturelle-histoire-du-14-juillet',
    getParentRoute: () => rootRouteImport,
  } as any)
const BatailleCulturelleDesLuttesPaysannesRoute =
  BatailleCulturelleDesLuttesPaysannesRouteImport.update({
    id: '/bataille-culturelle-des-luttes-paysannes',
    path: '/bataille-culturelle-des-luttes-paysannes',
    getParentRoute: () => rootRouteImport,
  } as any)
const R30SeptembreHalleTropismeRoute =
  R30SeptembreHalleTropismeRouteImport.update({
    id: '/30-septembre-halle-tropisme',
    path: '/30-septembre-halle-tropisme',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammeIndexRoute = ProgrammeIndexRouteImport.update({
  id: '/programme/',
  path: '/programme/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammeUuidRoute = ProgrammeUuidRouteImport.update({
  id: '/programme/$uuid',
  path: '/programme/$uuid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/30-septembre-halle-tropisme': typeof R30SeptembreHalleTropismeRoute
  '/bataille-culturelle-des-luttes-paysannes': typeof BatailleCulturelleDesLuttesPaysannesRoute
  '/bataille-culturelle-histoire-du-14-juillet': typeof BatailleCulturelleHistoireDu14JuilletRoute
  '/des-lendemains-meilleurs': typeof DesLendemainsMeilleursRoute
  '/entretien-emmanuel-negrier': typeof EntretienEmmanuelNegrierRoute
  '/festival-des-luttes-populaires': typeof FestivalDesLuttesPopulairesRoute
  '/la-charte': typeof LaCharteRoute
  '/la-fourmiliere-brule': typeof LaFourmiliereBruleRoute
  '/la-fourmiliere-de-lodeve': typeof LaFourmiliereDeLodeveRoute
  '/le-programme': typeof LeProgrammeRoute
  '/les-fourmilieres': typeof LesFourmilieresRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/participer-au-festival': typeof ParticiperAuFestivalRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/presse': typeof PresseRoute
  '/qui-sommes-nous': typeof QuiSommesNousRoute
  '/safia-dahani-les-extremes-droites-contemporaines': typeof SafiaDahaniLesExtremesDroitesContemporainesRoute
  '/programme/$uuid': typeof ProgrammeUuidRoute
  '/programme/': typeof ProgrammeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/30-septembre-halle-tropisme': typeof R30SeptembreHalleTropismeRoute
  '/bataille-culturelle-des-luttes-paysannes': typeof BatailleCulturelleDesLuttesPaysannesRoute
  '/bataille-culturelle-histoire-du-14-juillet': typeof BatailleCulturelleHistoireDu14JuilletRoute
  '/des-lendemains-meilleurs': typeof DesLendemainsMeilleursRoute
  '/entretien-emmanuel-negrier': typeof EntretienEmmanuelNegrierRoute
  '/festival-des-luttes-populaires': typeof FestivalDesLuttesPopulairesRoute
  '/la-charte': typeof LaCharteRoute
  '/la-fourmiliere-brule': typeof LaFourmiliereBruleRoute
  '/la-fourmiliere-de-lodeve': typeof LaFourmiliereDeLodeveRoute
  '/le-programme': typeof LeProgrammeRoute
  '/les-fourmilieres': typeof LesFourmilieresRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/participer-au-festival': typeof ParticiperAuFestivalRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/presse': typeof PresseRoute
  '/qui-sommes-nous': typeof QuiSommesNousRoute
  '/safia-dahani-les-extremes-droites-contemporaines': typeof SafiaDahaniLesExtremesDroitesContemporainesRoute
  '/programme/$uuid': typeof ProgrammeUuidRoute
  '/programme': typeof ProgrammeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/30-septembre-halle-tropisme': typeof R30SeptembreHalleTropismeRoute
  '/bataille-culturelle-des-luttes-paysannes': typeof BatailleCulturelleDesLuttesPaysannesRoute
  '/bataille-culturelle-histoire-du-14-juillet': typeof BatailleCulturelleHistoireDu14JuilletRoute
  '/des-lendemains-meilleurs': typeof DesLendemainsMeilleursRoute
  '/entretien-emmanuel-negrier': typeof EntretienEmmanuelNegrierRoute
  '/festival-des-luttes-populaires': typeof FestivalDesLuttesPopulairesRoute
  '/la-charte': typeof LaCharteRoute
  '/la-fourmiliere-brule': typeof LaFourmiliereBruleRoute
  '/la-fourmiliere-de-lodeve': typeof LaFourmiliereDeLodeveRoute
  '/le-programme': typeof LeProgrammeRoute
  '/les-fourmilieres': typeof LesFourmilieresRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/participer-au-festival': typeof ParticiperAuFestivalRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/presse': typeof PresseRoute
  '/qui-sommes-nous': typeof QuiSommesNousRoute
  '/safia-dahani-les-extremes-droites-contemporaines': typeof SafiaDahaniLesExtremesDroitesContemporainesRoute
  '/programme/$uuid': typeof ProgrammeUuidRoute
  '/programme/': typeof ProgrammeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/30-septembre-halle-tropisme'
    | '/bataille-culturelle-des-luttes-paysannes'
    | '/bataille-culturelle-histoire-du-14-juillet'
    | '/des-lendemains-meilleurs'
    | '/entretien-emmanuel-negrier'
    | '/festival-des-luttes-populaires'
    | '/la-charte'
    | '/la-fourmiliere-brule'
    | '/la-fourmiliere-de-lodeve'
    | '/le-programme'
    | '/les-fourmilieres'
    | '/mentions-legales'
    | '/participer-au-festival'
    | '/politique-de-confidentialite'
    | '/presse'
    | '/qui-sommes-nous'
    | '/safia-dahani-les-extremes-droites-contemporaines'
    | '/programme/$uuid'
    | '/programme/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/30-septembre-halle-tropisme'
    | '/bataille-culturelle-des-luttes-paysannes'
    | '/bataille-culturelle-histoire-du-14-juillet'
    | '/des-lendemains-meilleurs'
    | '/entretien-emmanuel-negrier'
    | '/festival-des-luttes-populaires'
    | '/la-charte'
    | '/la-fourmiliere-brule'
    | '/la-fourmiliere-de-lodeve'
    | '/le-programme'
    | '/les-fourmilieres'
    | '/mentions-legales'
    | '/participer-au-festival'
    | '/politique-de-confidentialite'
    | '/presse'
    | '/qui-sommes-nous'
    | '/safia-dahani-les-extremes-droites-contemporaines'
    | '/programme/$uuid'
    | '/programme'
  id:
    | '__root__'
    | '/'
    | '/30-septembre-halle-tropisme'
    | '/bataille-culturelle-des-luttes-paysannes'
    | '/bataille-culturelle-histoire-du-14-juillet'
    | '/des-lendemains-meilleurs'
    | '/entretien-emmanuel-negrier'
    | '/festival-des-luttes-populaires'
    | '/la-charte'
    | '/la-fourmiliere-brule'
    | '/la-fourmiliere-de-lodeve'
    | '/le-programme'
    | '/les-fourmilieres'
    | '/mentions-legales'
    | '/participer-au-festival'
    | '/politique-de-confidentialite'
    | '/presse'
    | '/qui-sommes-nous'
    | '/safia-dahani-les-extremes-droites-contemporaines'
    | '/programme/$uuid'
    | '/programme/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R30SeptembreHalleTropismeRoute: typeof R30SeptembreHalleTropismeRoute
  BatailleCulturelleDesLuttesPaysannesRoute: typeof BatailleCulturelleDesLuttesPaysannesRoute
  BatailleCulturelleHistoireDu14JuilletRoute: typeof BatailleCulturelleHistoireDu14JuilletRoute
  DesLendemainsMeilleursRoute: typeof DesLendemainsMeilleursRoute
  EntretienEmmanuelNegrierRoute: typeof EntretienEmmanuelNegrierRoute
  FestivalDesLuttesPopulairesRoute: typeof FestivalDesLuttesPopulairesRoute
  LaCharteRoute: typeof LaCharteRoute
  LaFourmiliereBruleRoute: typeof LaFourmiliereBruleRoute
  LaFourmiliereDeLodeveRoute: typeof LaFourmiliereDeLodeveRoute
  LeProgrammeRoute: typeof LeProgrammeRoute
  LesFourmilieresRoute: typeof LesFourmilieresRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  ParticiperAuFestivalRoute: typeof ParticiperAuFestivalRoute
  PolitiqueDeConfidentialiteRoute: typeof PolitiqueDeConfidentialiteRoute
  PresseRoute: typeof PresseRoute
  QuiSommesNousRoute: typeof QuiSommesNousRoute
  SafiaDahaniLesExtremesDroitesContemporainesRoute: typeof SafiaDahaniLesExtremesDroitesContemporainesRoute
  ProgrammeUuidRoute: typeof ProgrammeUuidRoute
  ProgrammeIndexRoute: typeof ProgrammeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/safia-dahani-les-extremes-droites-contemporaines': {
      id: '/safia-dahani-les-extremes-droites-contemporaines'
      path: '/safia-dahani-les-extremes-droites-contemporaines'
      fullPath: '/safia-dahani-les-extremes-droites-contemporaines'
      preLoaderRoute: typeof SafiaDahaniLesExtremesDroitesContemporainesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qui-sommes-nous': {
      id: '/qui-sommes-nous'
      path: '/qui-sommes-nous'
      fullPath: '/qui-sommes-nous'
      preLoaderRoute: typeof QuiSommesNousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presse': {
      id: '/presse'
      path: '/presse'
      fullPath: '/presse'
      preLoaderRoute: typeof PresseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-de-confidentialite': {
      id: '/politique-de-confidentialite'
      path: '/politique-de-confidentialite'
      fullPath: '/politique-de-confidentialite'
      preLoaderRoute: typeof PolitiqueDeConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participer-au-festival': {
      id: '/participer-au-festival'
      path: '/participer-au-festival'
      fullPath: '/participer-au-festival'
      preLoaderRoute: typeof ParticiperAuFestivalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/les-fourmilieres': {
      id: '/les-fourmilieres'
      path: '/les-fourmilieres'
      fullPath: '/les-fourmilieres'
      preLoaderRoute: typeof LesFourmilieresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/le-programme': {
      id: '/le-programme'
      path: '/le-programme'
      fullPath: '/le-programme'
      preLoaderRoute: typeof LeProgrammeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/la-fourmiliere-de-lodeve': {
      id: '/la-fourmiliere-de-lodeve'
      path: '/la-fourmiliere-de-lodeve'
      fullPath: '/la-fourmiliere-de-lodeve'
      preLoaderRoute: typeof LaFourmiliereDeLodeveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/la-fourmiliere-brule': {
      id: '/la-fourmiliere-brule'
      path: '/la-fourmiliere-brule'
      fullPath: '/la-fourmiliere-brule'
      preLoaderRoute: typeof LaFourmiliereBruleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/la-charte': {
      id: '/la-charte'
      path: '/la-charte'
      fullPath: '/la-charte'
      preLoaderRoute: typeof LaCharteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/festival-des-luttes-populaires': {
      id: '/festival-des-luttes-populaires'
      path: '/festival-des-luttes-populaires'
      fullPath: '/festival-des-luttes-populaires'
      preLoaderRoute: typeof FestivalDesLuttesPopulairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entretien-emmanuel-negrier': {
      id: '/entretien-emmanuel-negrier'
      path: '/entretien-emmanuel-negrier'
      fullPath: '/entretien-emmanuel-negrier'
      preLoaderRoute: typeof EntretienEmmanuelNegrierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/des-lendemains-meilleurs': {
      id: '/des-lendemains-meilleurs'
      path: '/des-lendemains-meilleurs'
      fullPath: '/des-lendemains-meilleurs'
      preLoaderRoute: typeof DesLendemainsMeilleursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bataille-culturelle-histoire-du-14-juillet': {
      id: '/bataille-culturelle-histoire-du-14-juillet'
      path: '/bataille-culturelle-histoire-du-14-juillet'
      fullPath: '/bataille-culturelle-histoire-du-14-juillet'
      preLoaderRoute: typeof BatailleCulturelleHistoireDu14JuilletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bataille-culturelle-des-luttes-paysannes': {
      id: '/bataille-culturelle-des-luttes-paysannes'
      path: '/bataille-culturelle-des-luttes-paysannes'
      fullPath: '/bataille-culturelle-des-luttes-paysannes'
      preLoaderRoute: typeof BatailleCulturelleDesLuttesPaysannesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/30-septembre-halle-tropisme': {
      id: '/30-septembre-halle-tropisme'
      path: '/30-septembre-halle-tropisme'
      fullPath: '/30-septembre-halle-tropisme'
      preLoaderRoute: typeof R30SeptembreHalleTropismeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programme/': {
      id: '/programme/'
      path: '/programme'
      fullPath: '/programme/'
      preLoaderRoute: typeof ProgrammeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programme/$uuid': {
      id: '/programme/$uuid'
      path: '/programme/$uuid'
      fullPath: '/programme/$uuid'
      preLoaderRoute: typeof ProgrammeUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R30SeptembreHalleTropismeRoute: R30SeptembreHalleTropismeRoute,
  BatailleCulturelleDesLuttesPaysannesRoute:
    BatailleCulturelleDesLuttesPaysannesRoute,
  BatailleCulturelleHistoireDu14JuilletRoute:
    BatailleCulturelleHistoireDu14JuilletRoute,
  DesLendemainsMeilleursRoute: DesLendemainsMeilleursRoute,
  EntretienEmmanuelNegrierRoute: EntretienEmmanuelNegrierRoute,
  FestivalDesLuttesPopulairesRoute: FestivalDesLuttesPopulairesRoute,
  LaCharteRoute: LaCharteRoute,
  LaFourmiliereBruleRoute: LaFourmiliereBruleRoute,
  LaFourmiliereDeLodeveRoute: LaFourmiliereDeLodeveRoute,
  LeProgrammeRoute: LeProgrammeRoute,
  LesFourmilieresRoute: LesFourmilieresRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  ParticiperAuFestivalRoute: ParticiperAuFestivalRoute,
  PolitiqueDeConfidentialiteRoute: PolitiqueDeConfidentialiteRoute,
  PresseRoute: PresseRoute,
  QuiSommesNousRoute: QuiSommesNousRoute,
  SafiaDahaniLesExtremesDroitesContemporainesRoute:
    SafiaDahaniLesExtremesDroitesContemporainesRoute,
  ProgrammeUuidRoute: ProgrammeUuidRoute,
  ProgrammeIndexRoute: ProgrammeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
