/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuiSommesNousRouteImport } from './routes/qui-sommes-nous'
import { Route as LesFourmilieresRouteImport } from './routes/les-fourmilieres'
import { Route as LeProgrammeRouteImport } from './routes/le-programme'
import { Route as LaCharteRouteImport } from './routes/la-charte'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgrammeIndexRouteImport } from './routes/programme/index'
import { Route as ProgrammeUuidRouteImport } from './routes/programme/$uuid'

const QuiSommesNousRoute = QuiSommesNousRouteImport.update({
  id: '/qui-sommes-nous',
  path: '/qui-sommes-nous',
  getParentRoute: () => rootRouteImport,
} as any)
const LesFourmilieresRoute = LesFourmilieresRouteImport.update({
  id: '/les-fourmilieres',
  path: '/les-fourmilieres',
  getParentRoute: () => rootRouteImport,
} as any)
const LeProgrammeRoute = LeProgrammeRouteImport.update({
  id: '/le-programme',
  path: '/le-programme',
  getParentRoute: () => rootRouteImport,
} as any)
const LaCharteRoute = LaCharteRouteImport.update({
  id: '/la-charte',
  path: '/la-charte',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammeIndexRoute = ProgrammeIndexRouteImport.update({
  id: '/programme/',
  path: '/programme/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammeUuidRoute = ProgrammeUuidRouteImport.update({
  id: '/programme/$uuid',
  path: '/programme/$uuid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/la-charte': typeof LaCharteRoute
  '/le-programme': typeof LeProgrammeRoute
  '/les-fourmilieres': typeof LesFourmilieresRoute
  '/qui-sommes-nous': typeof QuiSommesNousRoute
  '/programme/$uuid': typeof ProgrammeUuidRoute
  '/programme/': typeof ProgrammeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/la-charte': typeof LaCharteRoute
  '/le-programme': typeof LeProgrammeRoute
  '/les-fourmilieres': typeof LesFourmilieresRoute
  '/qui-sommes-nous': typeof QuiSommesNousRoute
  '/programme/$uuid': typeof ProgrammeUuidRoute
  '/programme': typeof ProgrammeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/la-charte': typeof LaCharteRoute
  '/le-programme': typeof LeProgrammeRoute
  '/les-fourmilieres': typeof LesFourmilieresRoute
  '/qui-sommes-nous': typeof QuiSommesNousRoute
  '/programme/$uuid': typeof ProgrammeUuidRoute
  '/programme/': typeof ProgrammeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/la-charte'
    | '/le-programme'
    | '/les-fourmilieres'
    | '/qui-sommes-nous'
    | '/programme/$uuid'
    | '/programme/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/la-charte'
    | '/le-programme'
    | '/les-fourmilieres'
    | '/qui-sommes-nous'
    | '/programme/$uuid'
    | '/programme'
  id:
    | '__root__'
    | '/'
    | '/la-charte'
    | '/le-programme'
    | '/les-fourmilieres'
    | '/qui-sommes-nous'
    | '/programme/$uuid'
    | '/programme/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LaCharteRoute: typeof LaCharteRoute
  LeProgrammeRoute: typeof LeProgrammeRoute
  LesFourmilieresRoute: typeof LesFourmilieresRoute
  QuiSommesNousRoute: typeof QuiSommesNousRoute
  ProgrammeUuidRoute: typeof ProgrammeUuidRoute
  ProgrammeIndexRoute: typeof ProgrammeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/qui-sommes-nous': {
      id: '/qui-sommes-nous'
      path: '/qui-sommes-nous'
      fullPath: '/qui-sommes-nous'
      preLoaderRoute: typeof QuiSommesNousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/les-fourmilieres': {
      id: '/les-fourmilieres'
      path: '/les-fourmilieres'
      fullPath: '/les-fourmilieres'
      preLoaderRoute: typeof LesFourmilieresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/le-programme': {
      id: '/le-programme'
      path: '/le-programme'
      fullPath: '/le-programme'
      preLoaderRoute: typeof LeProgrammeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/la-charte': {
      id: '/la-charte'
      path: '/la-charte'
      fullPath: '/la-charte'
      preLoaderRoute: typeof LaCharteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programme/': {
      id: '/programme/'
      path: '/programme'
      fullPath: '/programme/'
      preLoaderRoute: typeof ProgrammeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programme/$uuid': {
      id: '/programme/$uuid'
      path: '/programme/$uuid'
      fullPath: '/programme/$uuid'
      preLoaderRoute: typeof ProgrammeUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LaCharteRoute: LaCharteRoute,
  LeProgrammeRoute: LeProgrammeRoute,
  LesFourmilieresRoute: LesFourmilieresRoute,
  QuiSommesNousRoute: QuiSommesNousRoute,
  ProgrammeUuidRoute: ProgrammeUuidRoute,
  ProgrammeIndexRoute: ProgrammeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
